// ticketapp-react/app/tickets/new/page.jsx
'use client'
import TicketForm from '../../../components/TicketForm'
import { getSession } from '../../../lib/session'
import { createTicket } from '../../../lib/ticketsApi'
import toast from 'react-hot-toast'

export default function NewTicketPage(){
  if (typeof window !== 'undefined' && !getSession()){ window.location.href = '/auth/login'; return null }

  async function handleCreate(payload){ try{ await createTicket(payload); toast.success('Ticket created'); window.location.href = '/tickets' }catch(err){ toast.error('Failed to create ticket') } }

  return (
    <div>
      <h1 className="text-2xl font-bold mb-4">New Ticket</h1>
      <TicketForm onSubmit={handleCreate} />
    </div>
  )
}

// ticketapp-vue/src/views/tickets/New.vue
<template>
  <div>
    <h1 class="text-2xl font-bold mb-4">New Ticket</h1>
    <TicketForm :onSubmit="handleCreate" />
  </div>
</template>

<script>
import TicketForm from '../../components/TicketForm.vue'
import { createTicket } from '../../lib/ticketsApi'
import { getSession } from '../../lib/session'
import { useToast } from 'vue-toastification'
export default {
  components: { TicketForm },
  setup(){
    const toast = useToast()
    if (typeof window !== 'undefined' && !getSession()){ window.location.href = '/auth/login' }
    async function handleCreate(payload){ try{ await createTicket(payload); toast.success('Ticket created'); window.location.href='/tickets' }catch(e){ toast.error('Failed to create ticket') } }
    return { handleCreate }
  }
}
</script>
